import chatModel from '../models/chat.model.js';
import express from 'express';
const router = express.Router();
import protectedRoute from '../middleware/protectedRoute.js';
// router.get('/', protectedRoute, fetchAllChats);
// router.post('/', protectedRoute, accessChat);
// router.post('/group', protectedRoute, createGroupChat);
// router.put('/rename', protectedRoute, renameGroupChat);
// router.put('/removeGroup', protectedRoute, removeGroupChat);
// router.put('/addUser', protectedRoute, addUserToGroup);
export default router;
